"""rename department

Revision ID: 6f9fc58c6e7c
Revises: 43bc46115ee1
Create Date: 2024-07-23 17:58:54.760232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9fc58c6e7c'
down_revision = '43bc46115ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
    op.drop_table('departments')
    # ### end Alembic commands ###
